export const CITIES = [
  { value: 'TUYEN_QUANG', label: 'Tỉnh Tuyên Quang' },
  { value: 'LAO_CAI', label: 'Tỉnh Lào Cai' },
  { value: 'THAI_NGUYEN', label: 'Tỉnh Thái Nguyên' },
  { value: 'PHU_THO', label: 'Tỉnh Phú Thọ' },
  { value: 'BAC_NINH', label: 'Tỉnh Bắc Ninh' },
  { value: 'HUNG_YEN', label: 'Tỉnh Hưng Yên' },
  { value: 'HAI_PHONG', label: 'Thành phố Hải Phòng' },
  { value: 'NINH_BINH', label: 'Tỉnh Ninh Bình' },
  { value: 'QUANG_TRI', label: 'Tỉnh Quảng Trị' },
  { value: 'DA_NANG', label: 'Thành phố Đà Nẵng' },
  { value: 'QUANG_NGAI', label: 'Tỉnh Quảng Ngãi' },
  { value: 'GIA_LAI', label: 'Tỉnh Gia Lai' },
  { value: 'KHANH_HOA', label: 'Tỉnh Khánh Hoà' },
  { value: 'LAM_DONG', label: 'Tỉnh Lâm Đồng' },
  { value: 'DAK_LAK', label: 'Tỉnh Đắk Lắk' },
  { value: 'HO_CHI_MINH', label: 'Thành phố Hồ Chí Minh' },
  { value: 'DONG_NAI', label: 'Tỉnh Đồng Nai' },
  { value: 'TAY_NINH', label: 'Tỉnh Tây Ninh' },
  { value: 'CAN_THO', label: 'Thành phố Cần Thơ' },
  { value: 'VINH_LONG', label: 'Tỉnh Vĩnh Long' },
  { value: 'DONG_THAP', label: 'Tỉnh Đồng Tháp' },
  { value: 'CA_MAU', label: 'Tỉnh Cà Mau' },
  { value: 'AN_GIANG', label: 'Tỉnh An Giang' },
  { value: 'HA_NOI', label: 'Thành phố Hà Nội' },
  { value: 'HUE', label: 'Thành phố Huế' },
  { value: 'LAI_CHAU', label: 'Tỉnh Lai Châu' },
  { value: 'DIEN_BIEN', label: 'Tỉnh Điện Biên' },
  { value: 'SON_LA', label: 'Tỉnh Sơn La' },
  { value: 'LANG_SON', label: 'Tỉnh Lạng Sơn' },
  { value: 'QUANG_NINH', label: 'Tỉnh Quảng Ninh' },
  { value: 'THANH_HOA', label: 'Tỉnh Thanh Hoá' },
  { value: 'NGHE_AN', label: 'Tỉnh Nghệ An' },
  { value: 'HA_TINH', label: 'Tỉnh Hà Tĩnh' },
  { value: 'CAO_BANG', label: 'Tỉnh Cao Bằng' },
]
