export enum City {
  TUYEN_QUANG = 'TUYEN_QUANG',
  LAO_CAI = 'LAO_CAI',
  THAI_NGUYEN = 'THAI_NGUYEN',
  PHU_THO = 'PHU_THO',
  BAC_NINH = 'BAC_NINH',
  HUNG_YEN = 'HUNG_YEN',
  HAI_PHONG = 'HAI_PHONG',
  NINH_BINH = 'NINH_BINH',
  QUANG_TRI = 'QUANG_TRI',
  DA_NANG = 'DA_NANG',
  QUANG_NGAI = 'QUANG_NGAI',
  GIA_LAI = 'GIA_LAI',
  KHANH_HOA = 'KHANH_HOA',
  LAM_DONG = 'LAM_DONG',
  DAK_LAK = 'DAK_LAK',
  HO_CHI_MINH = 'HO_CHI_MINH',
  DONG_NAI = 'DONG_NAI',
  TAY_NINH = 'TAY_NINH',
  CAN_THO = 'CAN_THO',
  VINH_LONG = 'VINH_LONG',
  DONG_THAP = 'DONG_THAP',
  CA_MAU = 'CA_MAU',
  AN_GIANG = 'AN_GIANG',
  HA_NOI = 'HA_NOI',
  HUE = 'HUE',
  LAI_CHAU = 'LAI_CHAU',
  DIEN_BIEN = 'DIEN_BIEN',
  SON_LA = 'SON_LA',
  LANG_SON = 'LANG_SON',
  QUANG_NINH = 'QUANG_NINH',
  THANH_HOA = 'THANH_HOA',
  NGHE_AN = 'NGHE_AN',
  HA_TINH = 'HA_TINH',
  CAO_BANG = 'CAO_BANG',
  OTHER = 'OTHER',
}

export const CITIES = [
  { value: City.TUYEN_QUANG, label: 'Tỉnh Tuyên Quang' },
  { value: City.LAO_CAI, label: 'Tỉnh Lào Cai' },
  { value: City.THAI_NGUYEN, label: 'Tỉnh Thái Nguyên' },
  { value: City.PHU_THO, label: 'Tỉnh Phú Thọ' },
  { value: City.BAC_NINH, label: 'Tỉnh Bắc Ninh' },
  { value: City.HUNG_YEN, label: 'Tỉnh Hưng Yên' },
  { value: City.HAI_PHONG, label: 'Thành phố Hải Phòng' },
  { value: City.NINH_BINH, label: 'Tỉnh Ninh Bình' },
  { value: City.QUANG_TRI, label: 'Tỉnh Quảng Trị' },
  { value: City.DA_NANG, label: 'Thành phố Đà Nẵng' },
  { value: City.QUANG_NGAI, label: 'Tỉnh Quảng Ngãi' },
  { value: City.GIA_LAI, label: 'Tỉnh Gia Lai' },
  { value: City.KHANH_HOA, label: 'Tỉnh Khánh Hoà' },
  { value: City.LAM_DONG, label: 'Tỉnh Lâm Đồng' },
  { value: City.DAK_LAK, label: 'Tỉnh Đắk Lắk' },
  { value: City.HO_CHI_MINH, label: 'Thành phố Hồ Chí Minh' },
  { value: City.DONG_NAI, label: 'Tỉnh Đồng Nai' },
  { value: City.TAY_NINH, label: 'Tỉnh Tây Ninh' },
  { value: City.CAN_THO, label: 'Thành phố Cần Thơ' },
  { value: City.VINH_LONG, label: 'Tỉnh Vĩnh Long' },
  { value: City.DONG_THAP, label: 'Tỉnh Đồng Tháp' },
  { value: City.CA_MAU, label: 'Tỉnh Cà Mau' },
  { value: City.AN_GIANG, label: 'Tỉnh An Giang' },
  { value: City.HA_NOI, label: 'Thành phố Hà Nội' },
  { value: City.HUE, label: 'Thành phố Huế' },
  { value: City.LAI_CHAU, label: 'Tỉnh Lai Châu' },
  { value: City.DIEN_BIEN, label: 'Tỉnh Điện Biên' },
  { value: City.SON_LA, label: 'Tỉnh Sơn La' },
  { value: City.LANG_SON, label: 'Tỉnh Lạng Sơn' },
  { value: City.QUANG_NINH, label: 'Tỉnh Quảng Ninh' },
  { value: City.THANH_HOA, label: 'Tỉnh Thanh Hoá' },
  { value: City.NGHE_AN, label: 'Tỉnh Nghệ An' },
  { value: City.HA_TINH, label: 'Tỉnh Hà Tĩnh' },
  { value: City.CAO_BANG, label: 'Tỉnh Cao Bằng' },
]
